# Generated by Django 3.2.16 on 2023-01-08 00:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chronicle', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='chronicle',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='chronicle.chronicle'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='chronicle',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='chronicle.chronicle'),
            preserve_default=False,
        ),
    ]
