# Generated by Django 3.2.16 on 2023-01-08 00:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chronicle', '0003_alter_vampirecc_sire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vampirecc',
            name='sire',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vampire_sire', to='chronicle.character'),
        ),
    ]
