# Generated by Django 3.2.16 on 2023-01-08 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chronicle', '0005_alter_vampirecc_embrace_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vampirecc',
            name='embrace_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
