# Generated by Django 3.2.16 on 2023-01-08 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chronicle', '0006_alter_vampirecc_embrace_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='story',
            field=models.TextField(blank=True, null=True),
        ),
    ]
