# Generated by Django 3.2.16 on 2023-01-08 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chronicle', '0007_character_story'),
    ]

    operations = [
        migrations.AddField(
            model_name='vampirecc',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
