# Generated by Django 3.2.16 on 2023-01-08 01:41

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chronicle', '0009_plot_plotstages'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25)),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('chronicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chronicle.chronicle')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('sesion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chronicle.sesion')),
            ],
        ),
    ]
